name: "SQL Script Splitter Action"
author: "@nilsonneto"
description: "A GitHub action to split a SQL file into smaller files based on CTEs"
branding:
  icon: "grid"
  color: "gray-dark"
inputs:
  yaml-path:
    description: "Path on the workspace to the YAML config file"
    required: false
    default: "$GITHUB_WORKSPACE/sql_script_splitter.yaml"
runs:
  using: "composite"
  steps:
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - run: python $GITHUB_ACTION_PATH/sql_script_splitter.py yaml ${{ inputs.yaml-path }}
      shell: bash
